name: Build staging snapshot

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Targets to build (x86/64 ath79/genric)"
        required: false
        default: "x86/64 ath79/generic"
      config:
        description: "Extra lines to append to the config"
        required: false
        default: ""
      compile_only:
        description: 'Compile test but do not upload artifacts'
        required: false
        default: true
        type: boolean
      verbose:
        description: 'Enable verbose output'
        required: false
        default: true
        type: boolean
      build_toolchain:
        description: 'Build toolchain (with this not selected an external toolchain is used)'
        required: false
        default: false
        type: boolean
      use_ccache:
        description: 'Use ccache in build'
        required: false
        default: true
        type: boolean
      cache_tools:
        description: 'Cache target tools'
        required: false
        default: true
        type: boolean

jobs:
  setup:
    name: Setup cache
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.find_targets.outputs.target }}

    steps:
      - name: Setup Ubuntu
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install libncurses-dev qemu-utils clang-12

      - name: Cache openwrt.git
        uses: actions/cache@v3
        with:
          path: |
            openwrt/
          key: openwrt-repo-${{ github.sha }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: openwrt

      - name: Link caches
        run: |
          mkdir -p dl/
          ln -sf "$GITHUB_WORKSPACE/dl" "$GITHUB_WORKSPACE/openwrt/dl"

          mkdir -p feeds/
          ln -sf "$GITHUB_WORKSPACE/feeds" "$GITHUB_WORKSPACE/openwrt/feeds"

      - name: Determine cache keys
        run: |
          cd openwrt/
          echo "DL_CACHE_KEY=$(git log --pretty=%h -1 package/ tools/)" >> "$GITHUB_ENV"
          echo "FEEDS_CACHE_KEY=$(date +'%m/%d/%Y')" >> "$GITHUB_ENV"

      - name: Cache dl/
        uses: actions/cache@v3
        with:
          path: |
            dl/
          key: dl-${{ env.DL_CACHE_KEY }}
          restore-keys: |
            dl-

      - name: Cache feeds/
        uses: actions/cache@v3
        with:
          path: |
            feeds/
          key: feeds-${{ env.FEEDS_CACHE_KEY }}
          restore-keys: |
            feeds-

      - name: Make prereq
        run: |
          cd openwrt/
          make defconfig

      - name: Download sources
        run: |
          cd openwrt/
          make download -j$(nproc)

      - name: Cleanup
        run: |
          cd openwrt/
          rm -rf .config* staging_dir/toolchain-*

      - name: Update & Install feeds
        run: |
          cd openwrt/

          echo "src-git-full packages https://github.com/openwrt/packages.git" > feeds.conf
          echo "src-git-full luci https://github.com/openwrt/luci.git" >> feeds.conf
          echo "src-git-full routing https://github.com/openwrt/routing.git" >> feeds.conf
          echo "src-git-full telephony https://github.com/openwrt/telephony.git" >> feeds.conf

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Set targets
        id: find_targets
        run: |
          cd openwrt/
          if [ "${{ github.event.inputs.target }}" = "all" ]; then
            export TARGETS="$(perl ./scripts/dump-target-info.pl targets 2>/dev/null | awk '{ print $1 }')"
          else
            if [ -n "${{ github.event.inputs.target }}" ]; then
              export TARGETS="${{ github.event.inputs.target }}"
            else
              export TARGETS="x86/64 ath79/generic mediatek/mt7622"
            fi
          fi

          JSON='['
          FIRST=1
          for TARGET in $TARGETS; do
            [[ $FIRST -ne 1 ]] && JSON="$JSON"','
            JSON="$JSON"'"'"${TARGET}"'"'
            FIRST=0
          done
          JSON="$JSON"']'

          echo -e "\n---- targets ----\n"
          echo "$JSON"
          echo -e "\n---- targets ----\n"

          echo "::set-output name=target::$JSON"

  build:
    name: Build ${{ matrix.os }}/${{ matrix.target }}
    env:
      TOOLCHAIN_TYPE: external
    needs:
      - setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest]
        target: ${{fromJson(needs.setup.outputs.target)}}

    steps:
      - name: Cache openwrt.git
        uses: actions/cache@v3
        with:
          path: |
            openwrt/
          key: openwrt-repo-${{ github.sha }}

      - name: Link caches
        run: |
          mkdir -p dl/
          ln -sf "$GITHUB_WORKSPACE/dl" "$GITHUB_WORKSPACE/openwrt/dl"

          mkdir -p feeds/
          ln -sf "$GITHUB_WORKSPACE/feeds" "$GITHUB_WORKSPACE/openwrt/feeds"

          mkdir -p .ccache/
          ln -sf "$GITHUB_WORKSPACE/.ccache" "$GITHUB_WORKSPACE/openwrt/.ccache"

          mkdir -p tools/
          ln -sf "$GITHUB_WORKSPACE/tools" "$GITHUB_WORKSPACE/openwrt/tools"

      - name: Cache dl/
        uses: actions/cache@v3
        with:
          path: |
            dl/
          key: dl-${{ env.DL_CACHE_KEY }}
          restore-keys: |
            dl-

      - name: Cache .ccache/
        uses: actions/cache@v3
        if: ${{ github.event.inputs.use_ccache == 'true' }}
        with:
          path: |
            .ccache/
          key: ccache-${{ matrix.os }}-${{ matrix.target }}

      - name: Cache tools/
        uses: actions/cache@v3
        if: ${{ github.event.inputs.cache_tools == 'true' }}
        with:
          path: |
            tools/
          key: tools-${{ matrix.os }}-${{ matrix.target }}

      - name: Cache feeds/
        uses: actions/cache@v3
        with:
          path: |
            feeds/
          key: feeds-${{ env.FEEDS_CACHE_KEY }}
          restore-keys: |
            feeds-

      - name: Setup Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install libncurses-dev qemu-utils clang-12 tree device-tree-compiler

      - name: Initialization environment
        run: |
          TARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 1)
          SUBTARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 2)
          echo "TARGET=$TARGET" >> "$GITHUB_ENV"
          echo "SUBTARGET=$SUBTARGET" >> "$GITHUB_ENV"
      
      - name: Set verbose
        if: ${{ github.event.inputs.verbose == 'true' }}
        run: |
          echo "VERBOSE=V=s" >> "$GITHUB_ENV"

      - name: Enable toolchain build
        if: ${{ github.event.inputs.build_toolchain == 'true' }}
        run: |
          echo "TOOLCHAIN_TYPE=build" >> "$GITHUB_ENV"

      - name: Set configuration
        run: |
          cd openwrt/

          curl "https://downloads.openwrt.org/snapshots/targets/${{ matrix.target }}/config.buildinfo" > .config
          for CONFIG in ${{ github.event.inputs.config }}; do
            echo "CONFIG_$CONFIG" >> .config
          done

          echo "CONFIG_BPF_TOOLCHAIN_HOST=y" >> .config

          echo -e "\n---- config input ----\n"
          cat .config
          echo -e "\n---- config input ----\n"

          make defconfig

          echo -e "\n---- config post-defconfig ----\n"
          cat .config
          echo -e "\n---- config post-defconfig ----\n"

      - name: Enable CCache
        if: ${{ github.event.inputs.use_ccache == 'true' }}
        run: |
          cd openwrt/

          echo "CONFIG_CCACHE=y" >> .config

          make defconfig

      - name: Download toolchain
        run: |
          TOOLCHAIN_FILE=$(curl "https://downloads.openwrt.org/snapshots/targets/${{ matrix.target }}/sha256sums" \
            | sed -n -e 's/.*\(openwrt-toolchain.*\).tar.xz/\1/p')
          echo "TOOLCHAIN_FILE=$(pwd)/$TOOLCHAIN_FILE" >> "$GITHUB_ENV"
           
          wget -O - https://downloads.openwrt.org/snapshots/targets/${{ matrix.target }}/${TOOLCHAIN_FILE}.tar.xz \
            | tar --xz -xf -

      - name: Prepare toolchain
        run: |
          if [ "$TOOLCHAIN_TYPE" == "build" ]; then
            mkdir -p openwrt/staging_dir/
            ls -1 $TOOLCHAIN_FILE
            mv -f $TOOLCHAIN_FILE/$(ls -1 $TOOLCHAIN_FILE | grep toolchain) openwrt/staging_dir/
          else
            cd openwrt/
            ./scripts/ext-toolchain.sh --toolchain $TOOLCHAIN_FILE/$(ls -1 $TOOLCHAIN_FILE | grep toolchain) --overwrite-config --config ${{ matrix.target }}
          fi

      - name: Build tools
        run: |
          cd openwrt/
          make tools/install -j$(nproc) ${{ env.VERBOSE }} || \
            make tools/install V=s

      - name: Build toolchain
        run: |
          cd openwrt/
          make toolchain/install -j$(nproc) ${{ env.VERBOSE }} || \
            make toolchain/install V=s

      - name: Build target
        run: |
          cd openwrt/
          make target/compile -j$(nproc) IGNORE_ERRORS='n m' ${{ env.VERBOSE }} || \
            make target/compile IGNORE_ERRORS='n m' V=s BUILD_LOG=s

      - name: Build packages
        run: |
          cd openwrt/
          make package/compile -j$(nproc) IGNORE_ERRORS='n m' ${{ env.VERBOSE }} || \
            make package/compile IGNORE_ERRORS='n m' V=s BUILD_LOG=s

          make package/install -j$(nproc) ${{ env.VERBOSE }}

          make package/index CONFIG_SIGNED_PACKAGES= V=s

      - name: Build firmware
        run: |
          cd openwrt/
          make target/install -j$(nproc) ${{ env.VERBOSE }} || \
            make target/install V=s

      - name: Check bootargs
        run: |
          cd openwrt
          OPENWRT_DIR=$(pwd)
          cd build_dir
          echo $(ls | grep target | grep openwrt)
          cd $(ls | grep target | grep openwrt)
          echo $(ls | grep linux)
          cd $(ls | grep linux | grep $TARGET)
          echo $(ls | grep linux-5)
          cd $(ls | grep linux-5)

          echo Checking DTB
          touch $OPENWRT_DIR/dtb_files
          for file in $(find . -name \*.dtb); do
            echo $file;
            echo $file >> $OPENWRT_DIR/dtb_files
          done

          echo Have bootargs
          touch $OPENWRT_DIR/dtb_bootargs_files
          for file in $(find . -name \*.dtb); do
              fdtget -ts $file /chosen bootargs >&/dev/null && echo $file;
          done | sort -u >> $OPENWRT_DIR/dtb_bootargs_files

          for file in $(find . -name \*.dtb); do
              fdtget -ts $file /chosen bootargs >&/dev/null && echo $file;
          done | sort -u

          echo Have bootargs-append
          touch $OPENWRT_DIR/dtb_bootargs_append_files
          for file in $(find . -name \*.dtb); do
              fdtget -ts $file /chosen bootargs-append >&/dev/null && echo $file;
          done | sort -u >> $OPENWRT_DIR/dtb_bootargs_append_files

          for file in $(find . -name \*.dtb); do
              fdtget -ts $file /chosen bootargs-append >&/dev/null && echo $file;
          done | sort -u

      - name: Buildinfo
        run: |
          cd openwrt/
          make buildinfo V=s

      - name: JSON overview
        run: |
          cd openwrt/
          make json_overview_image_info V=s

      - name: Checksum
        run: |
          cd openwrt/
          make checksum V=s

      - name: Upload images
        if: ${{ github.event.inputs.compile_only == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ env.TARGET }}-images
          path: openwrt/bin/targets/${{ matrix.target }}/openwrt-${{ env.TARGET }}-*

      - name: Upload packages
        if: ${{ github.event.inputs.compile_only == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ env.TARGET }}-packages
          path: |
            openwrt/bin/targets/${{ matrix.target }}/packages/*.ipk
            !openwrt/bin/targets/${{ matrix.target }}/packages/kmod-*.ipk

      - name: Upload kmods
        if: ${{ github.event.inputs.compile_only == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ env.TARGET }}-kmods
          path: openwrt/bin/targets/${{ matrix.target }}/packages/kmod-*.ipk

      - name: Upload supplementary
        if: ${{ github.event.inputs.compile_only == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ env.TARGET }}-supplementary
          path: |
            openwrt/bin/targets/${{ matrix.target }}/*.buildinfo
            openwrt/bin/targets/${{ matrix.target }}/*.json
            openwrt/bin/targets/${{ matrix.target }}/*.manifest
            openwrt/bin/targets/${{ matrix.target }}/kernel-debug.tar.zst
            openwrt/bin/targets/${{ matrix.target }}/openwrt-imagebuilder*
            openwrt/bin/targets/${{ matrix.target }}/openwrt-sdk*
            openwrt/bin/targets/${{ matrix.target }}/sha256sums*

      - name: Upload supplementary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ env.TARGET }}-checkdts
          path: |
            openwrt/dtb_files
            openwrt/dtb_bootargs_files
            openwrt/dtb_bootargs_append_files

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ env.TARGET }}-logs
          path: openwrt/logs/
