FROM bitnami/minideb:latest

RUN install_packages gcc g++ ncurses-dev git rsync perl \
         tar bash patch findutils diffutils grep gzip \
         unzip bzip2 wget python3 python3-distutils \
         file make gawk coreutils ca-certificates \
         libelf-dev
RUN useradd buildbot

WORKDIR /home/buildbot
