name: 'Pull Request Labeler'
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read # to determine modified files (actions/labeler)
      pull-requests: write # to add labels to PRs (actions/labeler)

    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: ffittschen/pr-branch-labeler@fb82ac8ee94d19a8b183938ffca89f6c4031d10c
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
